remote_theme: Rudra-c0des/Hallownest-Theme
plugins:
  - jekyll-remote-theme

title: Rudra Patel
name: Rudra Patel
author: Rudra Patel
tagline: Every journey starts with a single step into the dark.

nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Experience
    url: /experience/
  - title: Contact
    url: /contact/